/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.getGreeting());
    }
    @Test public void weatherTest(){
        int [][]arr={
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
       String[] results= {"High Temp: 72", "Low Temp: 51", "Never saw temperature: 63", "Never saw temperature: 67", "Never saw temperature: 68", "Never saw temperature: 69"};
        assertEquals("this is supposed dataOfWeather func ", Arrays.toString(results) ,String.valueOf(Library.dataOfWeather((arr))));
    }
    @Test public void tallyFunc(){
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        String[] results={"Bush received the most votes!, and number of votes: 5 votes"};
        assertEquals("this is supposed trlly func",Arrays.toString(results),String.valueOf(Library.tally(votes)));

        List<String> votes2 = new ArrayList<>();
        votes2.add("Bush");
        votes2.add("Bush");
        votes2.add("Bush");
        votes2.add("Shrub");
        votes2.add("Hedge");
        votes2.add("Hedge");
        votes2.add("Hedge");
        votes2.add("Hedge");
        votes2.add("Shrub");
        votes2.add("Bush");
        votes2.add("Hedge");
        votes2.add("Bush");
        String[] results2={"Hedge received the most votes!, and number of votes: 5 votes","Bush received the most votes!, and number of votes: 5 votes"};
        assertEquals("this is supposed trlly func",Arrays.toString(results2),String.valueOf(Library.tally(votes2)));

    }
}
//[High Temp: 72, High Temp: 51, Never saw temperature: 63, Never saw temperature: 67, Never saw temperature: 68, Never saw temperature: 69]
