/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static Restaurant addRes(String name, int star, int price){
        Restaurant restaurant= new Restaurant(name,star,price);
        restaurant.test();
        System.out.println(restaurant);
        return restaurant;
    }
    public static Review gitReviewWithName(String name, String bodies, String authors, int stars, int price){
        Restaurant restaurant= new Restaurant(name,stars,price);
        String names=restaurant.getName();
       Review review=new Review(names,bodies,authors,stars);
        return review;
    }
    public static void addReviewFun(String name, int star, int price){
        Restaurant restaurant= new Restaurant(name,star,price);
        restaurant.addReview("Slowly Delaviry","ali",1);

    }
    public static void main(String[] args) {
        addRes("ahmad",7,7);
        gitReviewWithName("lolo","Fast Delivery","ahmad",5,80);
        addReviewFun("KFC",5,25);
    }
}
