/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void restaurantClass(){
//        Restaurant test=new Restaurant();
        String result="Restaurant{name='AHMAD', numberStar=5, priceGatogory=$1-$10 per person}";
        assertEquals("this for restaurant class: ",result,String.valueOf(Library.addRes("ahmad",6,9)));
    }
    @Test public void reviewClase(){
        Review review=new Review("fast","Ahmad",5);
        String result="this review from: AHMAD";
        assertEquals("this for review class: ",result,review.test());

    }
    @Test public void reviewWithName(){
        String result="Review{body='Fast Delivery', author='AHMAD', numStarts=5, nameOfRestaurant='LOLO'}";
        assertEquals("this for review with name: ",result,String.valueOf(Library.gitReviewWithName("lolo","Fast Delivery","ahmad",5,80)));
    }
    @Test public void AddReview(){
        Restaurant restaurant=new Restaurant("alia",5,50);
        restaurant.addReview("Slowly Delaviry","ali",1);
        String result="Test add review: this is old star: 5, and this new star after review: 1";
        assertEquals("this for add review: ",result,restaurant.addReviewTest());

    }
}
